package in.nic.cmf.dynamicgenerator;

public interface Constants {
	public static String[] emailIds = { "sndp_kool@hotmail.com",
			" snehasneha1@hotmail.com", " sonam_baller@hotmail.com",
			" sonamfine@hotmail.com", " sorang363@hotmail.com",
			" srk_sujan@hotmail.com", " steffi_yip@hotmail.com",
			" sth_ritu@hotmail.com", " still2get88@hotmail.com",
			" subash_hancy@hotmail.com", " subba80@msn.com",
			" subedinamita5@gmail.com", " sudikshya_123@hotmail.com",
			" sujata_453@hotmail.com", " sukritibaniya@hotmail.com",
			" surena_grg@hotmail.com", " svz29895@hotmail.com",
			" sweetchimas_chimsi@hotmail.com", " sweetgurl_gp_16@hotmail.com",
			" tamang_biresh@hotmail.com", " tan_wan_xuan@hotmail.com",
			" teddy_sophia@hotmail.com", " tesh_rocks@hotmail.com",
			" time@hotmail.com", " tinez_zenith@hotmail.com",
			" toran_35@hotmail.com", " trinatsh_4@hotmail.com",
			" tsering_dt17@hotmail.com", " tsewang2002@hotmail.com",
			" tshekisherpa@hotmail.com", " unam_eai@hotmail.com",
			" unique@hotmail.com", " unique01@hotmail.com",
			" unique02@hotmail.com", " unique03@hotmail.com",
			" unique07@hotmail.com", " unique1@hotmail.com",
			" unique100@hotmail.com", " unique103@hotmail.com",
			" unique104@hotmail.com", " unique105@hotmail.com",
			" unique106@hotmail.com", " unique108@hotmail.com",
			" unique109@hotmail.com", " unique11@hotmail.com",
			" unique110@hotmail.com", " unique12@hotmail.com",
			" unique13@hotmail.com", " unique15@hotmail.com",
			" unique16@hotmail.com", " unique18@hotmail.com",
			" unique21@hotmail.com", " unique22@hotmail.com",
			" unique23@hotmail.com", " unique24@hotmail.com",
			" unique3@hotmail.com", " unique30@hotmail.com",
			" unique33@hotmail.com", " unique37@hotmail.com",
			"unique41@hotmail.com", " unique42@hotmail.com",
			" unique43@hotmail.com", " unique44@hotmail.com",
			" unique47@hotmail.com", " unique48@hotmail.com",
			" unique5@hotmail.com", " unique50@hotmail.com",
			" unique54@hotmail.com", " unique56@hotmail.com",
			" unique58@hotmail.com", " unique59@hotmail.com",
			" unique60@hotmail.com", " unique62@hotmail.com",
			" unique63@hotmail.com", " unique64@hotmail.com",
			" unique65@hotmail.com", " unique66@hotmail.com",
			" unique67@hotmail.com", " unique68@hotmail.com",
			" unique7@hotmail.com", " unique70@hotmail.com",
			" unique71@hotmail.com", " unique73@hotmail.com",
			" unique74@hotmail.com", " unique75@hotmail.com",
			" unique76@hotmail.com", " unique77@hotmail.com",
			" unique78@hotmail.com", " unique81@hotmail.com",
			" unique82@hotmail.com", " unique83@hotmail.com",
			" unique84@hotmail.com", " unique86@hotmail.com",
			" unique87@hotmail.com", " unique88@hotmail.com",
			" unique89@hotmail.com", " unique9@hotmail.com",
			" unique90@hotmail.com", " unique92@hotmail.com",
			" unique94@hotmail.com", " unique95@hotmail.com",
			" unique97@hotmail.com", " unique98@hotmail.com",
			" unique99@hotmail.com", " unsuccessprawa@hotmail.com",
			"ups_4448@hotmail.com", " usha_aryal@hotmail.com",
			" verb@hotmail.com", " waiwenrocks@hotmail.com",
			" weixuan1996@hotmail.com", " xingyao_1991@hotmail.com",
			" yadito2002@hotmail.com", " yahoo@hotmail.com",
			" yakthumba99@hotmail.com", " yaky82@hotmail.com",
			" yanlingrace@hotmail.com", " yehuiqing2006@hotmail.com",
			" ygjx12345_@hotmail.com", " yoursasim_s@hotmail.com",
			" ysorguerrero@hotmail.com", " zoltrix_xound@hotmail.com",
			" zombiedragons_dead@hotmail.com", " neeten.000@gmail.com",
			" hi_gai@hi5.com", " rajanhere@yahoo.com",
			"nikeshoe11@hotmail.com", " rainerwong_1996@hotmail.com",
			" renie_1@hotmail.com", " sarah_hqm@hotmail.com",
			" sk8er_jia@hotmail.com", " star_rox_1995@hotmail.com",
			" wanlin-icepearl@hotmail.com", " xiianz-@hotmail.com",
			" yokeyean@hotmail.com", " hweejia_95@msn.com",
			" jamieee.th-onlyone@hotmail.com", " kenix200014@hotmail.com",
			" korea_rox_johnnybravo@hotmail.com",
			" littlekitty1995@hotmail.com", " ygjx12345_@hotmail.com",
			" amanda.chua2395@yahoo.com", " music_rocks_life@hotmail.com",
			" ariesbaby_ilurveyou@hotmail.com", " bluedogs_alf@hotmail.com",
			" cage_friends_forever@yahoo.com.sg",
			" dancefreak_jnlx@hotmail.com", " dawn_lyw@hotmail.com",
			" chanxiuming@yahoo.com.sg", " korea_rox_johnnybravo@hotmail.com",
			" joeywengshuyi@hotmail.com",
			" littlemissnaughty_bobo@hotmail.com",
			" luck_angel579@hotmail.com", " luckiness_celine@hotmail.com",
			" na_greennpink_sassygirl@hotmail.com", " nikeshoe11@hotmail.com",
			" piggysleeping123@hotmail.com", " piglet_en@hotmail.com",
			" pink3ygal@hotmail.com", " puffpuff_94@hotmail.com",
			" rebecca_underscore@hotmail.com", " sarah_hqm@hotmail.com",
			" staryyskyy_craziieboutyuu@hotmail.com",
			" sylvaniansilove@hotmail.com", " tainted-x3@live.com.sg",
			" ygjx12345_@hotmail.com", " bluedogs_alf@hotmail.com",
			" andrea_starlight@hotmail.com", " chocolate.pig@hotmail.com",
			" starey_char_night@hotmail.com", " piglet_en@hotmail.com",
			" piggysleeping123@hotmail.com", " darrenkoh@hotmail.com",
			" littlekitty1995@hotmail.com", " blueishgurl@hotmail.com",
			" forbidden-illusions@hotmail.com", " wantyou_dead@hotmail.com",
			" edmondlooi@yahoo.com", " preciousmummy@hotmail.com",
			" han_huiping@hotmail.com", " peppermintgurl06@hotmail.com",
			" littlemissnaughty_bobo@hotmail.com", " baby-felicia@hotmail.com",
			" chin305@hotmail.com", " blackpeaz@hotmail.com",
			" keeve48@hotmail.com", " noia_scribbles@yahoo.com",
			" clazzrepz@hotmail.com", " c_lionel@yahoo.com",
			" lixin.pang.2006@business.smu.edu.sg",
			" lolli_galz_95@hotmail.com", " marissachang95@hotmail.com",
			" piggy_mitch95@hotmail.com", " midnight.lake@hotmail.com",
			" nethania_lyf123@hotmail.com", " lookwhosenuts@hotmail.com",
			" summergirl_lia@hotmail.com", " p_chew@hotmail.com",
			" i_love_myself95@hotmail.com", " sheryl817@hotmail.com",
			" chaperon_sweet@hotmail.com", " angelkwan108@hotmail.com",
			" yuxuan1995@hotmail.com", " akuni_inukashinuyo@hotmail.com",
			" angelfrizz@hotmail.com", " angelworld_14@hotmail.com",
			" baby-felicia@hotmail.com", " baby-hartts@hotmail.com",
			" cally_88@hotmail.com", " carolyncst@hotmail.com",
			" cheeryapple95@hotmail.com", " choclattie_choc@hotmail.com",
			" chocobaberocks@hotmail.com", " choochristabel@hotmail.com",
			" end_s@hotmail.com", " hongyu1_love@msn.com",
			" isabel_bel_516@msn.com", " jasmine3095@hotmail.com",
			" lolli_galz_95@hotmail.com", " lonelyger95@hotmail.com",
			" loves_yellowie@hotmail.com", " mysticrs@hotmail.com",
			" prickyboy_twj@hotmail.com", " puppies-rocks@hotmail.com",
			" reginakoh_1995@hotmail.com", " rainbow_dolphine@hotmail.com",
			" sevenpigggys@hotmail.com", " sharon_d.s@hotmail.com",
			" sherlynyow_95@hotmail.com", " sylvaniansilove@hotmail.com",
			" sharlynnwu@hotmail.com", " unforgettable_euu_95@hotmail.com",
			" unforgettable_smile15@hotmail.com", " yokeyean@hotmail.com",
			" dark_kitty_26@hotmail.com", " christinejeremiah@hotmail.com",
			" piggygoh95@hotmail.com", " angelworld_14@hotmail.com",
			" eleanor_neo@hotmail.com", " sevenpigggys@hotmail.com",
			" colourfulcandycane@hotmail.com", " baby-hartts@hotmail.com",
			" jasminequekjiemin@hotmail.com", " keisha_miley@hotmail.com",
			" midnight.lake@hotmail.com", " koh_likeng@hotmail.com",
			" vestigeswiftz@hotmail.com", " alwaysruth1995@hotmail.com",
			" sherlynyow_95@hotmail.com", " abigailtay_1995@hotmail.com",
			" abovethenoise-@hotmail.com", " amandalee_1997@hotmail.com",
			" chocobaberocks@hotmail.com", " coolmat_95@hotmail.com",
			" faith_8396@hotmail.com", " faith_hengty@hotmail.com",
			" faith_wong_soke_yee@hotmail.com", " i_m_jelly@hotmail.com",
			" i-am-carissa@hotmail.com", " ifonly-me@hotmail.com",
			" james_pokemon@hotmail.com", " jumpjump-@hotmail.com",
			" melissa_soh96@hotmail.com", " meowingporcupine@hotmail.com",
			" alex_peng97@hotmail.com", " alien_sun@hotmail.com",
			" chesnachin@hotmail.com", " darren_low_96@hotmail.com" };
	public static String[] prefix = { "What", "How", "When", "Why", "Are",
			"Do", "Then", "Like", "able", "about", "account", "acid", "across",
			"act", "addition", "adjustment", "advertisement", "after", "again",
			"against", "agreement", "air", "all", "almost", "among", "amount",
			"amusement", "and", "angle", "angry", "animal", "answer", "ant",
			"any", "apparatus", "apple", "approval", "arch", "argument", "arm",
			"army", "art", "as", "at", "attack", "attempt", "attention",
			"attraction", "authority", "automatic", "awake", "baby", "back",
			"bad", "bag", "balance", "ball", "band", "base", "basin", "basket",
			"bath", "be", "beautiful", "because", "bed", "bee", "before",
			"behaviour", "belief", "bell", "bent", "berry", "between", "bird",
			"birth", "bit", "bite", "bitter", "black", "blade", "blood",
			"blow", "blue", "board", "boat", "body", "boiling", "bone", "book",
			"boot", "bottle", "box", "boy", "brain", "brake", "branch",
			"brass", "bread", "breath", "brick", "bridge", "bright", "broken",
			"brother", "brown", "brush", "bucket", "building", "bulb", "burn",
			"burst", "business", "but", "butter", "button", "by", "cake",
			"camera", "canvas", "card", "care", "carriage", "cart", "cat",
			"cause", "certain", "chain", "chalk", "chance", "change", "cheap",
			"cheese", "chemical", "chest", "chief", "chin", "church", "circle",
			"clean", "clear", "clock", "cloth", "cloud", "coal", "coat",
			"cold", "collar", "colour", "comb", "come", "comfort", "committee",
			"common", "company", "comparison", "competition", "aback",
			"abandoned", "abased", "abashed", "abated", "abducted", "aberrant",
			"aberration", "abhorred", "abhorrent", "abiding", "abject",
			"ablaze", "able", "abnormal", "aboard", "abolished", "abominable",
			"aboriginal  ", "aborted", "abortive", "abounding", "about",
			"above average", "abrasive", "abrupt", "absent", "absent-minded",
			"absolved", "absorbed", "absorbent", "absorbing", "abstemious",
			"abstract", "absurd", "abstracted", "abulic", "abused", "abusive",
			"abysmal   ", "abyssal", "accelerated", "acceptable", "accepted",
			"accepting", "accessible", "accident-prone", "accidental",
			"acclaimed", "acclimated", "accommodated", "accommodating",
			"accomplished", "accosted", "accosting", "accountable",
			"accredited", "acrid", "accurate", "accursed", "accusatory    ",
			"accused", "accusing", "acerbic", "aching", "acknowledged",
			"acquiescent", "acquisitive", "acrimonious", "activated", "active",
			"actualized", "accurate", "ad hoc", "adaptable", "adapted",
			"adamant", "addicted", "addled", "adept", "adequate",
			"adhered to    ", "adhering", "adhesive", "adjoined",
			"adjoined to", "adjoined with", "adjoining", "admirable",
			"admiration", "admired", "admiring", "admonished" };

	public static String[] wordsOne = { "time", "day", "cool", "hungry", "is",
			"can't", "you", "enjoy", "complete", "complex", "condition",
			"connection", "conscious", "control", "cook", "copper", "copy",
			"cord", "cork", "cotton", "cough", "country", "cover", "cow",
			"crack", "credit", "crime", "cruel", "crush", "cry", "cup", "cup",
			"current", "curtain", "curve", "cushion", "damage", "danger",
			"dark", "daughter", "day", "dead", "dear", "death", "debt",
			"decision", "deep", "degree", "delicate", "dependent", "design",
			"desire", "destruction", "detail", "development", "different",
			"digestion", "direction", "dirty", "discovery", "discussion",
			"disease", "disgust", "distance", "distribution", "division", "do",
			"dog", "door", "doubt", "down", "drain", "drawer", "dress",
			"drink", "driving", "drop", "dry", "dust", "ear", "early", "earth",
			"east", "edge", "education", "effect", "egg", "elastic",
			"electric", "end", "engine", "enough", "equal", "error", "even",
			"event", "ever", "every", "example", "exchange", "existence",
			"expansion", "experience", "expert", "eye", "face", "fact", "fall",
			"false", "family", "far", "farm", "fat", "father", "fear",
			"feather", "feeble", "feeling", "female", "fertile", "fiction",
			"field", "fight", "finger", "fire", "first", "fish", "fixed",
			"flag", "flame", "flat", "flight", "floor", "flower", "fly",
			"fold", "food", "foolish", "foot", "for", "force", "fork", "form",
			"forward", "fowl", "frame", "free", "frequent", "friend", "from",
			"front", "fruit", "full", "future", "garden", "general", "get",
			"girl", "give", "glass", "glove", "go", "goat", "gold", "good",
			"government", "grain", "grass", "great", "green", "grey", "grip",
			"group", "growth", "guide", "gun", "hair", "hammer", "hand",
			"hanging", "happy", "harbour", "hard", "harmony", "hat", "hate",
			"have", "he", "head", "healthy", "hear", "hearing", "heart",
			"heat", "help", "high", "history", "hole", "hollow", "hook",
			"hope", "horn", "horse", "hospital", "hour", "house", "how",
			"humour", "I", "ice", "idea", "if", "ill", "important", "impulse",
			"in", "increase", "industry", "ink", "insect", "instrument",
			"insurance", "interest", "invention", "iron", "island", "jelly",
			"jewel", "join", "journey", "judge", "jump", "keep", "kettle",
			"key", "kick", "kind", "kiss", "knee", "knife", "knot",
			"knowledge", "land", "language", "last", "late", "laugh", "law",
			"lead", "leaf", "learning", "leather", "left", "leg", "let",
			"letter", "level", "library", "lift", "light", "like", "limit",
			"line", "linen", "lip", "liquid", "list", "little", "living",
			"lock", "long", "look", "loose", "loss", "loud", "love", "low",
			"machine", "make", "male", "man", "manager", "map", "mark",
			"market", "married", "mass", "match", "material", "may", "meal",
			"measure", "meat", "medical", "meeting", "memory", "metal",
			"middle", "military", "milk", "mind", "mine", "minute", "mist",
			"mixed", "money", "monkey", "month", "moon", "morning", "mother",
			"motion", "mountain", "mouth", "move", "much", "muscle", "adopted",
			"adorable", "adored", "adoring", "adorned", "adrift", "adroit",
			"adult", "adulterated", "adulterous    ", "advanced",
			"adventurous", "adverse", "affable", "affected", "affection",
			"affectionate", "affirmed", "afflicted", "affluent", "affray",
			"affrayed", "affronted", "aflutter", "afraid", "against", "agape",
			"aggrandized", "aggravated", "aggressive", "aggrieved    ",
			"aghast", "agitated", "aglow", "agnostic", "agog", "agonized",
			"agonizing", "agony", "agoraphobic", "agreeable", "ahead", "ail",
			"ailed", "aimless", "airy", "alarmed", "alcoholic", "alien",
			"alienated", "alike   alive", "alleged", "allied", "allowed",
			"allowing", "allured", "alluring", "alone", "aloof", "almighty",
			"alright", "altruistic", "amateur", "amazed", "amazing",
			"ambiguous", "ambitious", "ambivalent", "ambushed", "amenable",
			"amiable  " };
	// eight basic, second category words to be chosen at random
	public static String[] wordsTwo = { "who", "awesome", "okay", "really",
			"turtle", "move", "look", "life", "music", "nail", "name",
			"narrow", "nation", "natural", "near", "necessary", "neck", "need",
			"needle", "nerve", "net", "new", "news", "night", "no", "noise",
			"normal", "north", "nose", "not", "note", "now", "number", "nut",
			"observation", "of", "off", "offer", "office", "oil", "old", "on",
			"only", "open", "operation", "opinion", "opposite", "or", "orange",
			"order", "organization", "ornament", "other", "out", "oven",
			"over", "owner", "page", "pain", "paint", "paper", "parallel",
			"parcel", "part", "past", "paste", "payment", "peace", "pen",
			"pencil", "person", "physical", "picture", "pig", "pin", "pipe",
			"place", "plane", "plant", "plate", "play", "please", "pleasure",
			"plough", "pocket", "point", "poison", "polish", "political",
			"poor", "porter", "position", "possible", "pot", "potato",
			"powder", "power", "present", "price", "print", "prison",
			"private", "probable", "process", "produce", "profit", "property",
			"prose", "protest", "public", "pull", "pump", "punishment",
			"purpose", "push", "put", "quality", "question", "quick", "quiet",
			"quite", "rail", "rain", "range", "rat", "rate", "ray", "reaction",
			"reading", "ready", "reason", "receipt", "record", "red", "regret",
			"regular", "relation", "religion", "representative", "request",
			"respect", "responsible", "rest", "reward", "rhythm", "rice",
			"right", "ring", "river", "road", "rod", "roll", "roof", "room",
			"root", "rough", "round", "rub", "rule", "run", "sad", "safe",
			"sail", "salt", "same", "sand", "say", "scale", "school",
			"science", "scissors", "screw", "sea", "seat", "second", "secret",
			"secretary", "see", "seed", "seem", "selection", "self", "send",
			"sense", "separate", "serious", "servant", "sex", "shade", "shake",
			"shame", "sharp", "sheep", "shelf", "ship", "shirt", "shock",
			"shoe", "short", "shut", "side", "sign", "silk", "silver",
			"simple", "sister", "size", "skin", "skirt", "sky", "sleep",
			"slip", "slope", "slow", "small", "smash", "smell", "smile",
			"smoke", "smooth", "snake", "sneeze", "snow", "so", "soap",
			"society", "sock", "soft", "amorous", "ample", "amuck", "amused",
			"amusing", "analytical", "analyzed", "anarchistic", "anchored",
			"ancient", "anemic", "anesthetized", "angry", "angst", "angsty*",
			"anguish", "anguished", "anhedonic", "animalistic", "animated",
			"animosity     ", "annihilated", "annoyed", "annoying", "anointed",
			"anonymous", "antagonistic", "antagonized", "anticipation",
			"antique", "antiquated", "antisocial", "antsy", "anxiety",
			"anxious", "apart", "apathetic", "apathy", "apologetic",
			"apoplectic", "apologized to", "appalled", "desiccated",
			"desirable", "desire", "desired", "desirous", "desolate",
			"despair", "despairing", "desperate", "despicable", "despised",
			"despondent", "detailed", "destitute", "destroyed", "destructive",
			"desultory", "detached", "detained", "deteriorated",
			"determined     ", "detest", "detestable", "detested",
			"detoxified", "devaluated", "devalued", "devastated", "developed",
			"deviant", "devil-may-care", "devious", "devoid", "devoid of...",
			"devoted", "devoured" };
	// eight basic, third category words to be chosen at random
	public static String[] wordsThr = { "money", "cheese", "run", "couch",
			"concept", "it", "cat", "factor", "solid", "some", "", "son",
			"song", "sort", "sound", "soup", "south", "space", "spade",
			"special", "sponge", "spoon", "spring", "square", "stage", "stamp",
			"star", "start", "statement", "station", "steam", "steel", "stem",
			"step", "stick", "sticky", "stiff", "still", "stitch", "stocking",
			"stomach", "stone", "stop", "store", "story", "straight",
			"strange", "street", "stretch", "strong", "structure", "substance",
			"such", "sudden", "sugar", "suggestion", "summer", "sun",
			"support", "surprise", "sweet", "swim", "system", "table", "tail",
			"take", "talk", "tall", "taste", "tax", "teaching", "tendency",
			"test", "than", "that", "the", "then", "theory", "there", "thick",
			"thin", "thing", "this", "thought", "thread", "throat", "through",
			"through", "thumb", "thunder", "ticket", "tight", "till", "time",
			"tin", "tired", "to", "toe", "together", "tomorrow", "tongue",
			"tooth", "top", "touch", "town", "trade", "train", "transport",
			"tray", "tree", "trick", "trouble", "trousers", "true", "turn",
			"twist", "umbrella", "under", "unit", "up", "use", "value",
			"verse", "very", "vessel", "view", "violent", "voice", "waiting",
			"walk", "wall", "war", "warm", "wash", "waste", "watch", "water",
			"wave", "wax", "way", "weather", "week", "weight", "well", "west",
			"wet", "wheel", "when", "where", "while", "whip", "whistle",
			"white", "who", "why", "wide", "will", "wind", "window", "wine",
			"wing", "winter", "wire", "wise", "with", "woman", "wood", "wool",
			"word", "work", "worm", "wound", "writing", "wrong", "year",
			"yellow", "yes", "yesterday", "you", "young", "devout",
			"diabolical", "diagnosed", "dictated to", "dictatorial",
			"didactic     ", "different", "difficult", "diffident", "diffused",
			"dignified", "diligent", "dim", "dimensionless", "diminished",
			"diminutive", "diplomatic", "dire", "direful", "direct",
			"directionless", "dirty", "disabled", "disaffected",
			"disagreeable", "disalike*", "disappointed   ", "disappointing",
			"disapproved of", "disapproving", "disarmed", "disbelieved",
			"disbelieving", "discardable", "discarded", "disciplined",
			"discomfit", "discombobulated", "disconcerted", "disconnected",
			"disconsolate", "discontent", "discontented", "discounted",
			"discouraged", "discouraging", "discredited", "discriminated ",
			
			
			"expr", "?import", "@import", "cmd=", "content=", "data:",
			"dynsrc=", "dynsrc=", "image/svg+xml", "implementation=",
			"javascript:", "list-style-image", "livescript:", "livescript:",
			"text/x-scriptlet", "vbscript:", "xss" };
	public static String[] wordsfour = {"discomfit", "discombobulated", "disconcerted", "disconnected"};
	// only one suffix
	public static String specialChars[] = { "☺", "☻", "♥", "♦", "♣", "♠", "•",
			"◘", "○", "◙", "♂", "♀", "♪", "♫", "☼", "►", "◄", "↕", "‼", "¶",
			"§", "▬", "↨", "↑", "↓", "→", "←", "∟", "↔", "▲", "▼", "!", "#",
			"$", "%", "&", "(", ")", "*", "+", ",", "-", ".", "/", "0", "1",
			"2", "3", "4", "5", "6", "7", "8", "9", ":", ";", "<", "=", ">",
			"?", "@" };
}
