package in.nic.cmf.searchengine;

public abstract interface ServiceConstants {
    public static final String CACHED_DATA        = "CACHED_DATA";
    public static final String PROPERTIES_EXT     = ".properties";
    public static final String CONFIG             = "config";
    public static final String ENTITY_TYPE        = "entitytype";
    public static final String ARTICLE            = "Article";
    public static final String GALLERY            = "Gallery";
    public static final String PACKAGE_NAME       = "packagename";
    public static final String METHOD_PREFIX      = "set";
    public static final String SUCCESS            = "success";
    public static final String MIME_TYPE_TEXT     = "text/plain";
    public static final String LAT                = "lat";
    public static final String LONG               = "long";
    public static final String LATITUDE           = "latitude";
    public static final String LONGITUDE          = "longitude";
    public static final String RADIUS             = "radius";
    public static final String GEO                = "geo";
    public static final String QT                 = "qt";
    public static final String USER_DATA          = "userData";
    public static final String SOLR_DATA          = "solrData";
    public static final String SOLR_KEY_LIST      = "solrkeylist";
    public static final String DEFAULT_CONDITION  = "defaultcondition";
    public static final String CONDAND            = "AND";
    public static final String CONDOR             = "OR";
    public static final String COND               = "cond";
    public static final String TEXT               = "text";
    public static final String HYPHEN5000         = "5000";
    public static final String QUERY              = "q";
    public static final String SOLR_QUERY_FORMAT  = "*:*";
    public static final String MAXIMUM_LIMIT      = "maximumlimit";
    public static final String LIMIT              = "limit";
    public static final String OFFSET             = "offset";
    public static final String ORDER_BY_DIR       = "orderbydir";
    public static final String COLON              = ":";
    public static final String ASCENDING          = "asc";
    public static final String DESCENDING         = "desc";
    public static final String TEXTC              = "text:";
    public static final String EMPTY_STRING       = "";
    public static final String SOLRURL            = "-solrurl";
    public static final String HIFEN              = "-";
    public static final String COMMA              = ",";
    public static final String Q                  = "q";
    public static final String DOT                = ".";
    public static final String RADIUSMIN          = "1";
    public static final String RADIUSMAX          = "250";
    public static final String SOLREXCEPTION      = "500";
    public static final String MD5                = "MD5";
    public static final String UTF8               = "UTF8";
    public static final String OK_STATUS          = "200";
    public static final String BAD_REQUEST_STATUS = "400";
    public static final String ID_LENGTH          = "13";

}
