var pathName = location.pathname;
var host = location.host;
var currentEntityItemId='';
var pathNameArray = pathName.split("/");
var domainName = pathNameArray[3];
var extPath   = "/" + pathNameArray[1] + "/extjs";
var cmsPath   = "/" + pathNameArray[1] + "/" + pathNameArray[2] + "/" + pathNameArray[3];
var mediaPath = "/" + "dataservices" + "/" + pathNameArray[2];
var domainName = pathNameArray[3];
//var dataservicesPath = "/" + "dataservices" + "/" + pathNameArray[2] + "/" + pathNameArray[3];
var dataservicesPath = "/cmf-1.0.0/" + "appflow/" + pathNameArray[3];
var loginUrl = cmsPath + "/login";
var stagingSiteUrl = "http://staging."+domainName+"/";
var dataPath = "/" + pathNameArray[1] + "/extjs/data";
var imagePath = "/" + pathNameArray[1] + "/extjs/images";
var itemsPerPage = 20;
//var authUrl = "/auth/"+ domainName + "/login";
var authUrl = "/cmf-1.0.0/auth/"+ domainName + "/Authentication";
var cmsUserName  = getCookie("authusername");
var userRole     = getCookie("aclrole");
var cmsApiKey    = getCookie("api_key");
var apacheNcmsData = "/ncmsdata/" + domainName;
//var aclStatus    = "&status=published";
var aclStatus    = "";
var aclSubQuery  = "&createdby="+cmsUserName+aclStatus;
var filterByMenu = '';
var globalEntityName = '';
var buildVersion = '5559';
var globalActiveTab = '';
var ItemThumbnailPath= '';
Ext.Ajax.timeout = 30000;
var pmsErrorpanel;
var cmsErrorpanel;
var adminErrorpanel;
var jtext = "";
var aForms = new Array();
var workflowForms = new Array();
var workflowUserMapForms = new Array();
var workflowUserMapProperties = '';
var itemsJsonData = {};
var layoutTemplatePath = '';
var npiMetaData = '';
var allFormsSaved = false;
var publisherRoleName = 'Publisher';
